#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Feb  2 10:02:44 2019

@author: tjwilliamson

Class to handle exceptions generated by the server
"""

class ServerError(Exception):
    pass

class ServerClientError(Exception):
    pass

class ReadMessageError(Exception):
    pass